spring.application.name=SpringSecEx
spring.security.user.name=manav
spring.security.user.password=gupta

#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/springsecurity
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.show-sql=true